---
title: "STAT222_HW7"
author: "Patrick Halkett"
date: "May 12, 2018"
output: html_document
---

```{r}
source("http://www.stat.uchicago.edu/~pmcc/courses/regress.R")

#Problem 1
y = c(9.1, 9.7, 10.1, 8.4, 7.1, 10.5, 9.8, 9.7, 9.8, 8.8, 8.0, 9.3, 8.1, 6.4, 6.3, 9.4, 7.9, 7.4, 7.0, 8.8, 10.4, 9.5, 10.4, 10.9, 12.4, 8.9, 9.1, 7.6, 9.2, 8.4, 9.4, 9.8, 11.2, 8.3, 10.3, 8.6, 10.0, 9.6, 10.2, 10.7, 10.5, 8.2, 9.3, 8.1, 8.2, 6.7, 9.4, 9.9, 8.6, 6.8, 10.1, 9.7, 9.0, 9.3, 7.8, 11.1, 9.4, 9.5, 10.5, 9.0, 7.9, 8.3, 9.8, 10.3, 7.9, 9.8, 9.3, 9.1, 10.6, 8.5, 12.7, 10.7, 10.1, 11.2, 10.6, 11.6, 10.4, 9.6, 10.7, 9.7, 11.7, 10.3, 10.7, 8.6, 10.2, 9.2, 9.6, 10.5, 10.4, 10.6, 9.5, 8.2, 10.1, 9.2, 8.8, 8.6, 7.9, 8.2, 10.1, 8.3, 10.7, 10.6, 9.1, 10.3, 8.5, 8.8, 11.0, 9.6, 8.3, 9.0, 11.5, 9.2, 10.9, 10.2, 10.8, 10.3, 10.4, 11.2, 10.2, 9.6)

#part 1
n <- length(y)
trt <- as.factor(rep(1:2,c(70,50)))
hbo <- trt
site <- gl(5,1,n)
rat <- gl(24,5,n)

df <- data.frame(trt,site,rat,y)
df

fit <- regress(y~site+trt,~rat)
summary(fit)
#fit$beta
#fit$beta.se
#fit$fitted
#fit$sigma

#mean(y)
mean_sites <- tapply(y,site,mean)
#mean_sites
mean_rats <- tapply(y,rat,mean)
#mean_rats
mean_trt <- tapply(y,trt,mean)
mean_trt

#part 2


#part 3
#B <- outer(trt,site,"==")
diff(tapply(y,hbo,mean))
anova(lm(y~trt))
summary(regress(y~trt,~rat))

#part 4
site1 <- y[c(1,6,11,16,21,26,31,36,41,46,51,56,61,66,71,76,81,86,91,96,101,106,111,116)]
site2 <- y[c(2,7,12,17,22,27,32,37,42,47,52,57,62,67,72,77,82,87,92,97,102,107,112,117)]
#site5 <- y[c(5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100,105,110,115,120)]
var(site2-site1)
anova(lm(y~site))
summary(regress(y~site,~rat))

#part 5
#fit0 <- regress(y~trt,~rat,kernel=1)
#fit1 <- regress(y~site+trt,~rat,kernel=1)
#X <- 2*(fit1$llik - fit0$llik)
#pchisq(X,4,lower.tail=FALSE)

#part 6
#summary(lm(y~site+hbo))
#summary(regress(y~site+hbo))

#part 7
#summary(lm(y~rat+site+hbo))
```

```{r}
#Problem 2
miles <- c(55,56,59,55,60,57, 39,42,43,41,41,42, 39,41,43,40,43,43, 44,44,42,39,40,43, 46,42,45,42,42,44)
brand <- rep(c(1:5),each=6)
p2matrix <- data.frame(brand,miles)
#p2matrix

#part 1
anova(lm(miles~as.factor(brand)))
#math done on paper

#part 2
summary(regress(miles~1,~as.factor(brand)))

#part 3
#The output in part 2 gives the estimate/variance/standard error via (and can be calculated from) 'as.factor(brand)'

#part 4
#Using a critical F-value calculator found online for 0.01 sig level, the two values are: 0.05 and 4.84
```

