---
title: "STAT222HW5"
author: "Patrick Halkett"
date: "April 26, 2018"
output: html_document
---
```{r}
options(warn=-1)
#options(warn=0)
```

```{r}
#Problem 1
faults <- c(32, 48, 538, 53, 81, 1901, 142, 197, 5689, 52, 244, 998, 112, 776, 3621, 262, 2625, 10012, 59, 536, 1348, 121, 1879, 4637, 980, 5698, 12880, 49, 67, 789, 100, 134, 3152, 233, 350, 9100, 79, 390, 1373, 164, 1255, 4912, 458, 3688, 13531, 85, 814, 1693, 206, 3394, 5838, 1633, 10022, 17117)
n <- length(faults)
alloc <- gl(3,1,n)
size <- gl(3,3,n)
seq <- gl(3,9,n)
alg <- gl(2,27,n)
lfaults <- log(faults)
#lfaults

#part 1
#fit1 <- lm(lfaults~seq*size*alloc*alg)
fit1 <- lm(lfaults~seq*size*alloc*alg - seq:size:alloc:alg)
round(anova(fit1),3)

#part 2
#fit2 <- lm(lfaults~seq*size*alloc+alg)
fit2 <- lm(lfaults~seq+size+alloc+alg+seq:size+seq:alloc+size:alloc+alloc:alg+seq:size:alloc)
round(anova(fit2),3)

#part 3
round(anova(fit2, fit1),3)

#part 4
res <- rstandard(fit2)
fvals <- fitted.values(fit2)

plot(fvals, res, ylim=c(-4,4), xlim=c(3,10), main="Std. Residuals of Fitted Values", pch=as.numeric(alg), xlab="Fitted Values", ylab="Std. Residuals", abline(h=0, lty=2))
legend("topright", legend=c("Algorithm 1", "Algorithm 2"), pch=as.numeric(levels(alg)), cex=0.7)

#part 5
#I do not recommend pooling as standard, since it may lead to biased estimates of the error
#Only consider pooling a term into error if:
#There are 10 or less error degrees of freedom
#The term under consideration from pooling has an F < 2

#part 6
z = lfaults - fvals
sum(fvals*z)
#sum of y(hat)*z = 0 means orthogonal

#part 7
#(y, alloc, mean)
#tapply(yhat, alloc, mean)
#tapply(z, alloc, sum)

```

```{r}
#Problem 2
amyl <- c(391.8, 427.7, 486.6, 469.2, 383.1, 338.9, 283.7, 269.3, 311.8, 388.1, 426.6, 436.8, 408.8, 355.5, 309.4, 278.7, 367.4, 468.1, 499.8, 444.0, 429.0, 304.5, 309.9, 313.0, 301.3, 352.9, 376.3, 373.6, 377.5, 308.8, 234.3, 197.1, 271.4, 296.4, 393.0, 364.8, 364.3, 279.0, 255.4, 198.3, 300.3, 346.7, 334.7, 386.6, 329.2, 261.3, 239.4, 216.7, 292.7, 422.6, 443.5, 438.5, 350.6, 305.9, 319.9, 286.7, 283.3, 359.5, 431.2, 398.9, 383.9, 342.8, 283.2, 266.5, 348.1, 381.9, 388.3, 413.7, 408.4, 332.2, 287.9, 259.8, 269.7, 380.9, 389.4, 400.3, 340.5, 288.6, 260.9, 221.9, 284.0, 357.1, 420.2, 412.8, 309.5, 271.8, 253.6, 254.4, 235.3, 339.0, 453.4, 371.9, 313.0, 333.7, 289.5, 246.7) 
n <- length(amyl)
temp <- rep(c(40,35,30,25,20,15,13,10), 12)
ftemp <- as.factor(temp)
var <- gl(2, 24, n)
levels(var) <- c("B73", "O43")
gt <- gl(2, 48, n)
levels(gt) <- c("25", "13")
lamyl <- log(amyl)
#lamyl

#part 1
fit3 <- lm(lamyl~ftemp*var*gt)
round(anova(fit3),3)

#part 2
x1 = seq(10,40,by=0.75)
y1 = 4.8453+0.0895*(x1)-0.00162*(x1)^2
x2 = seq(10,40,by=0.75)
y2 = 4.5031+0.1070*(x2)-0.00197*(x2)^2
y1max = max(y1, na.rm=F)
y2max = max(y2, na.rm=F)
y1max
y2max

par(mfrow=c(2,1));
plot(ftemp, lamyl, main="Box-Plot (Temp as Factor) with Subplot (Temp as Var.)");plot(temp, lamyl, cex=0.7,pch=as.numeric(var), col=as.numeric(var));legend("topright", bty="n", legend=paste("var", levels(var)), pch=c(1,2), col=c(1,2), cex=0.7);lines(y1, col="black");lines(y2, col="red");

#part 3


#part 4

#part 5
xx <- one.single.fuck
```